### PR TITLE
Fixed incorrect ordering of events (was date DESC).

### PR DESCRIPTION
**Pull request by parndt**
I've also taken the opportunity to use partials to make this easier to extend and to maintain.

### CODE REVIEW

**Comment by lachlanhardy** [comment]
And yet, still ERB?

**Comment by parndt** [comment]
Yup. Do you want something else?

**Comment by pat** [comment]
I think best to keep it to ERB - or more to the point, to HTML - instead of HAML or Slim or other such things. While generally I opt for HAML on personal projects, I'd rather this site be something that people of all skill levels can contribute to more easily. HTML is a lower bar, hence my preference for sticking with ERB.

**Comment by lachlanhardy** [comment]
Fair enough :)

**Pull request merged**
