### PR TITLE
Add US West 2018 Camp

### PR DESCRIPTION
**Pull request by elliotthilaire**
Added the details for US West August 2018 camp that I could extrapolate from http://west.railscamp.us

### CODE REVIEW

**Comment by elliotthilaire** [comment]
@bobbilee19 Can you please confirm this is ok.

**Comment by bobbilee19** [comment]
@elliotthilaire Hey how did u get that prepare-schedule link? I have it hidden

**Comment by elliotthilaire** [comment]
@bobbilee19 

I spotted it in the last entry for the US West camp
https://github.com/pat/railscamps.com/commit/e761fc526096041a009f5dc6ce0808276f8cf989

I'll delete that section. Then we can add it when it's ready.

**Comment by bobbilee19** [comment]
@elliotthilaire oh ok i was nervous haha ok so i changed up the page west.railscamp.us/packing u can use this

**Comment by elliotthilaire** [comment]
I've updated it to point to the new link.

**Comment by bobbilee19** [comment]
ship it!

**Comment by pat** [comment]
Merged :) Travis will auto-deploy soon, but Cloudfront will take its time updating the cache (may take a day or so - I'm yet to get that configured quite correctly).

**Pull request merged**
