### PR TITLE
Adding RC USA East Coast 2016

### PR DESCRIPTION
**Pull request by lachlanhardy**
Been a long time since I've done a PR for a project that I didn't have commit rights to. Let me know if I screwed something up.

Also, RAILS CAMP USA EAST COAST! 

(could we get longer? Probably. We're the Java of event naming.)

### CODE REVIEW

**Comment by parndt** [comment]
Looks good to me; @pat can you review & deploy please

**Comment by lachlanhardy** [comment]
:palm_tree: :camel: :snowman:

**Comment by pat** [comment]
Merged and deployed :)

**Comment by lachlanhardy** [comment]
Thanks, @pat!

**Pull request merged**
